/*
 * Generated by ISE 19.05.10.3187 GPL Edition - linux-x86-64
 */

#include "eif_eiffel.h"
#include "eif_project.h"
#include "egc_include.h"
#include "eoffsets.h"

#ifdef __cplusplus
extern "C" {
#endif
extern void F1_23();
extern EIF_REFERENCE F1_14();
extern void F891_6605();
extern void F894_6847();
extern void F444_3187();
extern void F885_6487();
extern void F52_1233();
extern EIF_REFERENCE F52_1220();
extern EIF_BOOLEAN F52_1232();
extern EIF_BOOLEAN F52_1240();
extern void F52_1242();
extern void F52_1243();
extern void F52_1244();
extern void egc_routine_tables_init (void);

long *eif_area_table = (long *)0;
long *eif_lower_table = (long *)0;
extern char *(*R2[])();
extern char *(*R6[])();
extern char *(*R3[])();

extern char *(*R4[])();

extern char *(*R5[])();



extern void egc_init_plug (void); 
void egc_init_plug (void)
{
	egc_prof_enabled = (EIF_INTEGER) 0;
	egc_correct_mismatch = (void (*)(EIF_REFERENCE)) F1_23;
	egc_twin = (EIF_REFERENCE (*)(EIF_REFERENCE)) F1_14;
	egc_strmake = (void (*)(EIF_REFERENCE, EIF_INTEGER)) F891_6605;
	egc_str32make = (void (*)(EIF_REFERENCE, EIF_INTEGER)) F894_6847;
	egc_arrmake = (void (*)(EIF_REFERENCE, EIF_INTEGER, EIF_INTEGER)) F444_3187;
	egc_str_count_offset = + _LNGOFF_1_1_0_2_;
	egc_str_hash_offset = + _LNGOFF_1_1_0_0_;
	egc_str32_count_offset = + _LNGOFF_1_1_0_2_;
	egc_str32_hash_offset = + _LNGOFF_1_1_0_0_;
	egc_routdisp_fl = (void (*)(EIF_REFERENCE, EIF_POINTER, EIF_POINTER, EIF_POINTER, EIF_REFERENCE, EIF_BOOLEAN, EIF_INTEGER)) F885_6487;
	egc_is_scoop_capable = 1;
	egc_set_exception_data = (void (*)(EIF_REFERENCE, EIF_INTEGER, EIF_BOOLEAN, EIF_INTEGER, EIF_INTEGER, EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE, EIF_INTEGER, EIF_BOOLEAN)) F52_1233;
	egc_set_last_exception = (void (*)(EIF_REFERENCE, EIF_REFERENCE)) F52_1232;
	egc_last_exception = (EIF_REFERENCE (*)(EIF_REFERENCE)) F52_1220;
	egc_is_code_ignored = (EIF_BOOLEAN (*)(EIF_REFERENCE, EIF_INTEGER)) F52_1240;
	egc_once_raise = (void (*)(EIF_REFERENCE, EIF_REFERENCE)) F52_1242;
	egc_init_exception_manager = (void (*)(EIF_REFERENCE)) F52_1243;
	egc_free_preallocated_trace = (void (*)(EIF_REFERENCE)) F52_1244;

	egc_str_dtype = 892;

	egc_str32_dtype = 894;
	egc_arr_dtype = 443;
	egc_tup_dtype = 811;
	egc_disp_rout_id = 3145;
	egc_copy_rout_id = 18;
	egc_is_equal_rout_id = 11;

	egc_sp_char = 0x0218;
	egc_sp_wchar = 0x0220;
	egc_sp_bool = 0x021F;
	egc_sp_uint8 = 0x0214;
	egc_sp_uint16 = 0x0213;
	egc_sp_uint32 = 0x0216;
	egc_sp_uint64 = 0x021D;
	egc_sp_int8 = 0x021B;
	egc_sp_int16 = 0x021C;
	egc_sp_int32 = 0x0217;
	egc_sp_int64 = 0x021E;
	egc_sp_real32 = 0x021A;
	egc_sp_real64 = 0x0219;
	egc_sp_pointer = 0x0215;
	egc_sp_ref = 0x0212;

	egc_uint8_dtype = 835;
	egc_uint16_dtype = 841;
	egc_uint32_dtype = 838;
	egc_uint64_dtype = 850;
	egc_int8_dtype = 814;
	egc_int16_dtype = 847;
	egc_int32_dtype = 844;
	egc_int64_dtype = 826;
	egc_bool_dtype = 829;
	egc_real32_dtype = 817;
	egc_char_dtype = 823;
	egc_wchar_dtype = 820;
	egc_real64_dtype = 832;
	egc_point_dtype = 883;

	egc_exception_dtype = 61;
	egc_except_emnger_dtype = 51;

	egc_ce_type = egc_ce_type_init;

	egc_ce_exp_type = egc_ce_exp_type_init;
	egc_fsystem = egc_fsystem_init;
	egc_system_mod_init = egc_system_mod_init_init;
	egc_partab = egc_partab_init;
	egc_partab_size = egc_partab_size_init;
	exception_stack_managed = (EIF_BOOLEAN) 0;
	egc_ecreate = (void (**)(EIF_REFERENCE, EIF_REFERENCE)) R2;
	egc_exp_create = (void (**)(EIF_REFERENCE)) R6;
	egc_edispose = (void (**)(void)) R3;
	egc_copy = (void (**)(EIF_REFERENCE, EIF_REFERENCE)) R4;
	egc_is_equal = (EIF_BOOLEAN (**)(EIF_REFERENCE, EIF_REFERENCE)) R5;
	egc_ce_rname = egc_ce_rname_init;
	egc_fnbref = egc_fnbref_init;
	egc_fsize = egc_fsize_init;

	egc_system_name = "eiffel-studio-contract-timing";
	egc_system_location = "/home/ilgiz/eiffel-studio-contract-timing/EIFGENs/eiffel-studio-contract-timing/F_code";
	egc_compiler_tag = 38;
	egc_project_version = 1613139659;
	egc_has_old_special_semantic = 0;
	scount = 908;

	egc_rcount = 1;
	egc_ridx = 0;
	egc_rlist = (char**) eif_malloc (sizeof(char*)*egc_rcount);
	egc_rcdt = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rlist[0] = "APPLICATION.make";
	egc_rcdt[0] = 0;
	
	
	egc_platform_level = 0x00000D00;
	egc_routine_tables_init();
}

void egc_rcdt_init (void)
{
	if (egc_rcdt[0] == 0) {
		egc_rcdt[0] = 175; /* APPLICATION */
	}
}

#ifdef __cplusplus
}
#endif
