
#ifndef _C1_an1_
#define _C1_an1_

#ifdef __cplusplus
extern "C" {
#endif

extern EIF_REFERENCE F1_4(EIF_REFERENCE);
extern EIF_REFERENCE F1_5(EIF_REFERENCE);
extern EIF_BOOLEAN F1_6(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_BOOLEAN F1_7(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_BOOLEAN F1_8(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_BOOLEAN F1_9(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_BOOLEAN F1_10(EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE);
extern EIF_BOOLEAN F1_11(EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE);
extern EIF_BOOLEAN F1_12(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_BOOLEAN F1_13(EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE);
extern EIF_REFERENCE F1_14(EIF_REFERENCE);
extern void F1_15(EIF_REFERENCE, EIF_REFERENCE);
extern void F1_16(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_REFERENCE F1_17(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_REFERENCE F1_18(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_REFERENCE F1_19(EIF_REFERENCE);
extern EIF_REFERENCE F1_20(EIF_REFERENCE);
extern EIF_REFERENCE F1_21(EIF_REFERENCE, EIF_REFERENCE);
extern void F1_22(EIF_REFERENCE, EIF_REFERENCE);
extern void F1_23(EIF_REFERENCE);
static EIF_REFERENCE F1_24_body(EIF_REFERENCE);
extern EIF_REFERENCE F1_24(EIF_REFERENCE);
extern EIF_REFERENCE F1_25(EIF_REFERENCE);
extern EIF_REFERENCE F1_26(EIF_REFERENCE);
extern void F1_27(EIF_REFERENCE, EIF_REFERENCE);
static EIF_REFERENCE F1_28_body(EIF_REFERENCE);
extern EIF_REFERENCE F1_28(EIF_REFERENCE);
extern void F1_29(EIF_REFERENCE);
extern void F1_30(EIF_REFERENCE);
extern void F1_31(EIF_REFERENCE);
extern EIF_REFERENCE F1_32(EIF_REFERENCE);
extern EIF_POINTER F1_33(EIF_REFERENCE);
extern EIF_REFERENCE F1_34(EIF_REFERENCE);
extern void F1_1(EIF_REFERENCE, int);
extern void EIF_Minit1(void);
extern void F22_145(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_BOOLEAN F289_2537(EIF_REFERENCE);
extern void F61_1401(EIF_REFERENCE, EIF_REFERENCE);
extern void F891_6607(EIF_REFERENCE, EIF_REFERENCE);
extern void F22_142(EIF_REFERENCE);
extern void F893_6731(EIF_REFERENCE, EIF_REFERENCE);
extern char *(*R11[])();
extern char *(*R2934[])();
extern char *(*R18[])();
extern char *(*R3875[])();
extern char *(*R28[])();

#ifdef __cplusplus
}
#endif

#endif
