
#ifndef _C1_op16_
#define _C1_op16_

#ifdef __cplusplus
extern "C" {
#endif

static EIF_CHARACTER_8 F23_191_body(EIF_REFERENCE);
extern EIF_CHARACTER_8 F23_191(EIF_REFERENCE);
static EIF_REFERENCE F23_192_body(EIF_REFERENCE);
extern EIF_REFERENCE F23_192(EIF_REFERENCE);
extern EIF_BOOLEAN F23_193(EIF_REFERENCE);
extern EIF_BOOLEAN F23_194(EIF_REFERENCE);
extern EIF_BOOLEAN F23_195(EIF_REFERENCE);
extern EIF_CHARACTER_8 F23_196(EIF_REFERENCE);
extern EIF_REFERENCE F23_197(EIF_REFERENCE);
extern void EIF_Minit16(void);

#ifdef __cplusplus
}
#endif

#endif
