
#ifndef _C1_sy3_
#define _C1_sy3_

#ifdef __cplusplus
extern "C" {
#endif

extern EIF_REFERENCE F3_35(EIF_REFERENCE, EIF_REFERENCE);
extern void F3_36(EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE);
extern void F3_37(EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE);
extern void F3_38(EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE);
extern EIF_INTEGER_32 F3_39(EIF_REFERENCE, EIF_REFERENCE);
extern void EIF_Minit3(void);
extern EIF_INTEGER_32 F537_3095(EIF_REFERENCE);
extern EIF_INTEGER_32 F29_754(EIF_REFERENCE);
extern EIF_BOOLEAN F106_1814(EIF_REFERENCE);
extern EIF_INTEGER_32 F545_3095(EIF_REFERENCE);
extern char *(*R4681[])();

#ifdef __cplusplus
}
#endif

#endif
